# PostgreSQL configuration
image:
  registry: "registry.redhat.io"
  repository: "rhel8/postgresql-13"
  tag: "latest"
  pullPolicy: "IfNotPresent"

# Authentication configuration
auth:
  enablePostgresUser: true
  postgresPassword: "postgres123"
  username: "airflow"
  password: "airflow123"
  database: "airflow"

# Primary instance configuration
primary:
  name: "primary"
  persistence:
    enabled: true
    size: 20Gi
    storageClass: ""
    accessMode: "ReadWriteOnce"
  
  # Resources
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  # Security context for OpenShift
  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  
  # Pod security context
  podSecurityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true

# Service configuration
service:
  type: "ClusterIP"
  port: 5432
  annotations: {}

# Network policy
networkPolicy:
  enabled: false

# Metrics and monitoring
metrics:
  enabled: false