{{- if .Values.global.imageRegistry.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enterprise-data-platform.fullname" . }}-registry-secret
  namespace: {{ .Values.global.tenant.namespace }}
  labels:
    {{- include "enterprise-data-platform.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "enterprise-data-platform.imagePullSecret" . }}
{{- end }}