apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  user-password: {{ .Values.auth.password | b64enc | quote }}
  {{- if .Values.auth.enablePostgresUser }}
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
  {{- end }}