apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-scheduler
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    component: scheduler
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      {{- include "airflow.selectorLabels" . | nindent 6 }}
      component: scheduler
  template:
    metadata:
      labels:
        {{- include "airflow.selectorLabels" . | nindent 8 }}
        component: scheduler
    spec:
      serviceAccountName: {{ include "airflow.serviceAccountName" . }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
      containers:
        - name: scheduler
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - airflow
            - scheduler
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          securityContext:
            runAsUser: {{ .Values.scheduler.securityContext.runAsUser }}
            runAsGroup: {{ .Values.scheduler.securityContext.runAsGroup }}
            runAsNonRoot: {{ .Values.scheduler.securityContext.runAsNonRoot }}
          volumeMounts:
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath: airflow.cfg
              readOnly: true
            {{- if .Values.dags.persistence.enabled }}
            - name: dags
              mountPath: /opt/airflow/dags
            {{- end }}
            {{- if .Values.logs.persistence.enabled }}
            - name: logs
              mountPath: /opt/airflow/logs
            {{- end }}
      volumes:
        - name: airflow-config
          configMap:
            name: {{ include "airflow.fullname" . }}-config
        {{- if .Values.dags.persistence.enabled }}
        - name: dags
          persistentVolumeClaim:
            claimName: {{ include "airflow.fullname" . }}-dags-pvc
        {{- end }}
        {{- if .Values.logs.persistence.enabled }}
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "airflow.fullname" . }}-logs-pvc
        {{- end }}